name: daily_planner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2

flutter:
  assets:
    - asset/image/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


